spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: hola
    driver-class-name: com.mysql.cj.jdbc.Driver
